-- ground.script
local pieces = { "ground0", "ground1", "ground2", "ground3",
"ground4", "ground5" } -- <1>

function init(self) -- <2>
	self.speed = 360  -- Speed in pixels/s
end

function update(self, dt) -- <3>
	for i, p in ipairs(pieces) do -- <4>
		local pos = go.get_position(p)
		if pos.y <= -228 then -- <5>
			pos.y = 1368 + (pos.y + 228)
		end
		pos.y = pos.y - self.speed * dt -- <6>
		go.set_position(pos, p) -- <7>
	end
end